import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coach House CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 w-full bg-white dark:bg-gray-800 shadow-md z-10">
          <div className="flex items-center justify-between px-4 py-2">
            <h1 className="text-lg font-bold text-black dark:text-white">Coach House CRM</h1>
            <button className="text-black dark:text-white" onClick={() => toggleDarkMode()}>
              Toggle Dark Mode
            </button>
          </div>
        </nav>
        <div className="flex">
          <aside className="w-64 bg-gray-200 dark:bg-gray-900 p-4">
            <ul>
              <li><a href="/dashboard">Dashboard</a></li>
              <li><a href="/contacts">Contacts</a></li>
            </ul>
          </aside>
          <main className="flex-1 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}

function toggleDarkMode() {
  const body = document.body;
  if (body.classList.contains('dark')) {
    body.classList.remove('dark');
  } else {
    body.classList.add('dark');
  }
}
